### ISSUE TITLE
OreDic entries don't account for stack size. (Moved by request)

### ISSUE THREAD

**Issue by Claycorp** [jaredlll08/MTLib#2]
#### Issue Description: 
When setting an item to an oredic entry IE: ```<ore:ingotIron> * 5``` you can't use the quantity modifier ```* 5``` because it will just ignore the whole stack. See: BeetoGuy/BetterWithMods#317

#### What happens:
Entry is totally ignored as if it was null.

#### What you expected to happen: 
An oredic stack to be placed in the recipe.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): 
https://pastebin.com/P2bG0wWd
http://i.imgur.com/RK0hoIT.png Matching recipe that is created with the above script.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): 
https://pastebin.com/ppTpn2yP

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Crafttweaker: 3.0.24

#### Your most recent log file where the issue was present: 

https://pastebin.com/T9Vpe0gg

**Comment by oa10712** [comment]
Was this actually fixed? It seems to still be affecting version 1.0.3
